version: '3.8'

networks:
  net-01:
    driver: bridge

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: soloanvill
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soloanvill
    ports:
      - 5432:5432
    networks:
      - net-01

  IMAGE_NAME:
    image: ACCOUNT_NAME/IMAGE_NAME:IMAGE_VERSION
    restart: no
    ports:
      - 80:8080
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      db:
        condition: service_started
    networks:
      - net-01