version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soloanvill
    ports:
      - 5432:5432

  IMAGE_NAME:
    image: rtav3d/IMAGE_NAME:IMAGE_VERSION
    restart: no
    ports:
      - 80:8080
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      db:
        condition: service_started