version: '3.8'

networks:
  net-01:
    driver: bridge

services:
  db:
    image: bitnami/postgresql:16.3.0-debian-12-r16
    restart: always
    environment:
      POSTGRESQL_USERNAME: soloanvill
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: soloanvill
    ports:
      - 5432:5432
    networks:
      - net-01

  IMAGE_NAME:
    image: ACCOUNT_NAME/IMAGE_NAME:IMAGE_VERSION
    restart: no
    ports:
      - 80:8080
    environment:
      SOLOANVILL_DATABASE_HOST: db
      SOLOANVILL_DATABASE_PORT: 5432
      SOLOANVILL_DATABASE_USER: soloanvill
      SOLOANVILL_DATABASE_PASSWORD: password
      SOLOANVILL_JENKINS_HOST: 127.0.0.1
      SOLOANVILL_JENKINS_LOGIN: JENKINS_LOGIN
      SOLOANVILL_JENKINS_TOKEN: JENKINS_TOKEN
    depends_on:
      db:
        condition: service_started
    networks:
      - net-01
    command: sh -c "sleep 1 && /usr/local/bin/soloanvill_backend"
