version: '3.8'

networks:
  net-01:
    driver: bridge

services:
  db:
    image: bitnami/postgresql:16.3.0-debian-12-r16
    restart: always
    environment:
      POSTGRESQL_USERNAME: soloanvill
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: soloanvill
    ports:
      - 5432:5432
    networks:
      - net-01

  IMAGE_NAME:
    image: ACCOUNT_NAME/IMAGE_NAME:IMAGE_VERSION
    restart: no
    ports:
      - 80:8080
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      SOLOANVILL_DATABASE_HOST: db
    depends_on:
      db:
        condition: service_started
    networks:
      - net-01